spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: SpringCloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
server:
  port: 8000

# mybatis配置
mybatis:
  type-aliases-package: com.zh.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

# Eureka配置 注册服务
eureka:
  client:
    service-url: # web监控页面
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: SpringCloud-provider-dept-8000 # 修改Eureka上的默认描述信息
    prefer-ip-address: true # 为true可以显示服务的ip地址

# info信息
info:
  app.name: SpringCloud-provider-dept
  user:
    name: zhh
    email: 1425279634@qq.com
      
---
spring:
  profiles: test
  application:
    name: SpringCloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
server:
  port: 8001

# mybatis配置
mybatis:
  type-aliases-package: com.zh.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

# Eureka配置 注册服务
eureka:
  client:
    service-url: # web监控页面
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: SpringCloud-provider-dept-8001 # 修改Eureka上的默认描述信息
    prefer-ip-address: true # 为true可以显示服务的ip地址

# info信息
info:
  app.name: SpringCloud-provider-dept
  user:
    name: zhh
    email: 1425279634@qq.com
