spring:
  profiles:
    active: 7002

---
spring:
  profiles: 7001
server:
  port: 7001
# Eureka配置
eureka:
  instance:
    hostname: Eureka7001 # Eureka服务端的实例名称
  client:
    register-with-eureka: false # 表示是否向Eureka注册中心注册自己
    fetch-registry: false # 为false：表示自己为注册中心
    service-url: # web监控页面
      # 单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群
      defaultZone: http://localhost:7002/eureka/,http://127.0.0.1:7003/eureka/


---
spring:
  profiles: 7002
server:
  port: 7002
# Eureka配置
eureka:
  instance:
    hostname: Eureka7002 # Eureka服务端的实例名称
  client:
    register-with-eureka: false # 表示是否向Eureka注册中心注册自己
    fetch-registry: false # 为false：表示自己为注册中心
    service-url: # web监控页面
      defaultZone: http://localhost:7001/eureka/,http://127.0.0.1:7003/eureka/


